sudo: false
language: java

jdk:
  # openjdk7 only on ubuntu precise, see https://docs.travis-ci.com/user/reference/precise/#jvm-clojure-groovy-java-scala-vm-images
  #- openjdk7
  - openjdk8
  - openjdk11
  - openjdk17

cache:
  directories:
    - $HOME/.m2

os:
  - linux
